_VERSION: 10 # Do not touch this line!

provider: lastfm # lastfm, listenbrainz
username: ""

# What to show on the small image and text
smallImage: profile
# logo: Provider logo
# profile: Profile picture from provider
# none: No small image (also disables small text)
smallText: username
# username: "Scrobbling as [Username] on [Provider]"
# provider: "Scrobbling on [Provider]"
# none: No small image

# Show "elapsed" time since start of song
# and "remaining" time until end of song (if available)
# If both are enabled, Discord shows a progress bar
# Note that both values tend to be inaccurate, especially if you pause
showElapsedTime: true
showRemainingTime: true

# Buttons to show on the Rich Presence
# NOTE: You can't see the buttons on your own profile
button1: profile
button2: github
# song: "View Song" (links to the scrobble provider)
# songlink:
#   If possible, links to Songlink/Odesli
#   Otherwise, links to the scrobble provider
# song-lastfm: Links to Last.FM
# song-listenbrainz: "Listen to Song"
#   Links to an instant playlist on ListenBrainz
# song-musicbrainz: links to MusicBrainz
# profile: "<Provider> Profile"
# github: "Scrobble Rich Presence"
# none: No button

# Special integration with Nintendo Music
# Requires songs to be scrobbled as by "Nintendo Co., Ltd."
# Works with Pano Scrobbler
nintendoMusic:
  # Uses per-song art instead of album art
  useSongArt: true
  # Formats Splatoon tracks into something like this:
  #   Calamari Inkantation
  #   by Squid Sisters
  #   Splatoon
  formatSplatoonArtist: true

# Disable when another app's Rich Presence is detected
# Requires joining https://discord.gg/lanyard
disableOnPresence:
  any: false
  listening: true
  custom: # Application IDs or names (case-insensitive)
    # "" is required for IDs
    - "12345678901234567890"
    - Apple Music

# ADVANCED
# You probably don't need to touch these

# lastFmApiKey: ""
# discordClientId: ""
# listenBrainzAPIURL: http://localhost:8100
