_VERSION: 10

provider: lastfm
username: ""

smallImage: profile
smallText: username

showElapsedTime: true
showRemainingTime: true

button1: profile
button2: github

nintendoMusic:
  useSongArt: true
  formatSplatoonArtist: true

disableOnPresence:
  any: false
  listening: true
  custom:
    - "12345678901234567890"
    - Apple Music
# lastFmApiKey: ""
# discordClientId: ""
# listenBrainzAPIURL: http://localhost:8100
